from configs.ToRURAL import SOURCE_DATA_CONFIG,TARGET_DATA_CONFIG, EVAL_DATA_CONFIG, TARGET_SET, TEST_DATA_CONFIG
MODEL = 'ResNet'


IGNORE_LABEL = -1
MOMENTUM = 0.9
NUM_CLASSES = 7

SNAPSHOT_DIR = './log/DCA/2rural'

#Hyper Paramters
WEIGHT_DECAY = 0.0005
LEARNING_RATE = 1e-2
NUM_STEPS_MAX = 7500  # for learning rate poly
NUM_STEPS_STOP = 5001  # Use damping instead of early stopping
FIRST_STAGE_STEP = 2000  # for first stage
PREHEAT_STEPS = int(NUM_STEPS_MAX / 20)  # for warm-up
POWER = 0.9  # lr poly power
EVAL_EVERY = 500
GENERATE_PSEDO_EVERY = 500
MULTI_LAYER = False
IGNORE_BG = True
PSEUDO_SELECT = True

TARGET_SET = TARGET_SET
SOURCE_DATA_CONFIG=SOURCE_DATA_CONFIG
TARGET_DATA_CONFIG=TARGET_DATA_CONFIG
EVAL_DATA_CONFIG=EVAL_DATA_CONFIG
TEST_DATA_CONFIG = TEST_DATA_CONFIG
